contact/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.contact, name='contact'),

]

floral_design/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('basket', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('privacy', views.privacy, name='privacy'),
    path('delivery_info', views.delivery_info, name='delivery_info'),
]

contact/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(max_length=20, null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    message = models.TextField(max_length=600, null=True, blank=True)
    added_info = models.TextField(max_length=600, null=True, blank=True)
    date = models.DateField(auto_now=True)
    time = models.TimeField(auto_now=True)

    def __str__(self):
        return self.name

contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        """
        Add placeholders and classes, remove auto-generated
        labels and set autofocus on first field
        """
        super().__init__(*args, **kwargs)
        placeholders = {
            'name': 'Name',
            'email': 'Email Address',
            'phone': 'Phone Number',
            'message': 'Your Message',
            'added_info': 'Any other Request',
        }

        self.fields['name'].widget.attrs['autofocus'] = True
        for field in self.fields:
            if field != 'added_info':
                if self.fields[field].required:
                    placeholder = f'{placeholders[field]} *'
                else:
                    placeholder = placeholders[field]
                self.fields[field].widget.attrs['placeholder'] = placeholder
                self.fields[field].widget.attrs['class'] = 'side-print'
            self.fields[field].label = False

contact/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.contrib import messages
from .models import Contact
from .forms import ContactForm


def contact(request):
    """
    Handles contact message instance
    """

    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            messages.success(request, 'You message has been\
            sent, we will get back to \
                within two working days.')
            return redirect('home')
        else:
            messages.error(request, 'You have made an error')
            return redirect('home')
    else:
        contact_form = ContactForm()

    template = 'contact/contact.html'

    context = {
        'contact_form': contact_form
    }
    return render(request, template, context)

contact/templates/contact/contact.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %} - Contact{% endblock %}

{% block extra_css%}
    <link rel="stylesheet" href="">
{% endblock %}

{% block page_header %}
    <div class="container header-container">
        <div class="row mt-5">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <h1 class="main-print mb-4 contact-header-h1">Contact Us</h1>
            </div>
        </div>
    
        <div class="row">
            <div class="col">
                <h2 class="side-print contact-header-h2">Please fill in the form below</h2>
                <form action="{% url 'contact' %}" method="POST" class="mt-3" id="contact-form">
                    {% csrf_token %}
                    <label for="id_name">Full Name *</label>
                    <input type="text" name="name" maxlength="20" pattern=".*\S+.*" class="shadow form-background form-control" required="True" id="id_name">
                    <label for="id_email">Email *</label>
                    <input type="email" name="email" maxlength="20" class="shadow form-background textinput form-control" required="True" id="id_email">
                    <label for="id_phone">Phone Number *</label>
                    <input type="text" name="phone" maxlength="254" pattern=".*\S+.*" class="shadow form-background textinput form-control" required="True" id="id_phone">
                    <label for="id_message">Write your message below *</label>
                    <textarea type="text" name="message" maxlength="600" pattern=".*\S+.*" class="shadow form-background textinput form-control" required="True" id="id_message"></textarea>
                    <label for="id_added_info">Any added information fill in below</label>
                    <textarea type="text" name="added_info" maxlength="600" pattern=".*\S+.*" class="shadow form-background textinput form-control" id="id_added_info"></textarea>
                    <button class="button submit-btn" type="submit">
                        Submit
                    </button>
                </form>
            </div>
        </div>
    </div>
    
{% endblock %}